### ISSUE TITLE
Android Warning: OnRequestTrackTransparencyFinished is never used

### ISSUE THREAD

**Issue by rmgomez** [ByteBrewIO/ByteBrewUnitySDK#2]
There is a very annoying warning in the console when in Android Mode:

`Assets\ByteBrewSDK\Scripts\ByteBrew.cs(22,41): warning CS0067: The event 'ByteBrew.OnRequestTrackTransparencyFinished' is never used`

SDK Version: 0.0.9
Unity Version: 2020.3.38f1

**Comment by ByteBrewIO** [comment]
@rmgomez, thank you for pointing this out. This warning does not affect anything, you can proceed by ignoring it. We will look into removing the warning in our next upcoming SDK update.
