### ISSUE TITLE
How experimental is this SDK?

### ISSUE THREAD

**Issue by AldeRoberge** [ByteBrewIO/ByteBrewUnitySDK#4]
I really wanted to love ByteBrew, coming from Game Analytics and being really burned by their bad documentation and overall poor first user experience.

I usually like to take a quick peek under the hood before going through the acquisition of a new tool…
But what I found was a little discouraging :

![image](https://github.com/ByteBrewIO/ByteBrewUnitySDK/assets/4276275/8d61409c-ac8b-4c29-8a43-021f5a4252df)

I'm not trying to be overly harsh, since this is a free product after all. But the first script users come into contact when using your tool should at least be rock solid.

If you need a maintainer, I can take some time to refactor the script and propose a pull request.

**Comment by cameronhozouri** [comment]
Hi @AldeRoberge ,
Thanks for passing this along! The SDK is incredibly stable. As you can tell by our SDK history, we don't ship any updates unless everything has been thoroughly tested.

We've noted the items you highlighted. The naming of different methods you mentioned are independent functions that are connected to very different parts of the platform. Also the "IsInitilized" method is no longer in use and will be removed on future updates. As noted in your image, the method "IsByteBrewInitialized" is newest version to use.

Always feel free to shoot us a message at [contact@bytebrew.io](mailto:contact@bytebrew.io) with any other info, where we can directly note items to our team.
