### ISSUE TITLE
Error "linking object 'macCatalyst'" when building for iOS Simulator

### ISSUE THREAD

**Issue by magicjar** [ByteBrewIO/ByteBrewUnitySDK#5]
Unity Version: 2021.3.17f1
Bytebre Version: 0.1.5

Issue:
Building for 'iOS-simulator', but linking in object file (~/Builds/PROD/iOS/iOS/IL2CPP/APPSTORE_DEBUG/1.6.0-build.330/Libraries/ByteBrewSDK/Plugins/iOS/libByteBrewiOSPlugin.a[x86_64][2](ByteBrewUserNotificationCenter.o)) built for 'macCatalyst'

![Screenshot 2024-06-24 102142](https://github.com/ByteBrewIO/ByteBrewUnitySDK/assets/9734293/c24cb537-eace-416a-88c0-006764d56a8f)

I have already tried to add macCatalyst as an excluded architecture, but it still doesn't work.

I have other plugins, including Facebook, AdMob, Firebase, and some others. In my last attempt, I temporarily removed Bytebrew, and the build was successful.

This was only a debug build. When I build for release, it does build successfully, but I still hope it gets fixed.

**Comment by cameronhozouri** [comment]
Hello magicjar,
ByteBrew cannot be tested on iOS Simulators and must be tested on a real iOS devices for Unity. For any additional questions, please email our support at contact@bytebrew.io.
